# sample round config
# all endowments can be specified either as a single number or a list of endowments, one for each player in each group

players_per_group: 2
cash_endowment: 20
allow_short: true
period_length: 120

states:
  X:
    prob_weight: 1
  Y:
    prob_weight: 1

asset_structure:
  A:
    is_etf: false
    endowment: [15, 10]
    payoffs:
      X: 2
      Y: 0
  B:
    is_etf: false
    endowment: [10, 5]
    payoffs:
      X: -1
      Y: 3
  D:
    is_etf: true
    endowment: 0
    etf_weights:
      A: 1
      B: 1
