# sample round config
# all endowments can be specified either as a single number or a list of endowments, one for each player in each group

players_per_group: 2
cash_endowment: 20
allow_short: false
period_length: 100

states:
  X:
    prob_weight: 1
  Y:
    prob_weight: 2
  Z:
    prob_weight: 3

asset_structure:
  A:
    is_etf: false
    endowment: [10, 20]
    payoffs:
      X: 2
      Y: 1
      Z: 0
  B:
    is_etf: false
    endowment: [5, 15]
    payoffs:
      X: 0
      Y: 2
      Z: 1
  C:
    is_etf: false
    endowment: 5
    payoffs:
      X: 1
      Y: 0
      Z: 2
  D:
    is_etf: true
    endowment: 5
    etf_weights:
      A: 1
      B: 2
      C: 0
